### ISSUE TITLE
Use elpy and live-py-plugin side-by-side will trigger the error `user-error: Current buffer has no associated file`.e

### ISSUE THREAD

**Issue by hongyi-zhao** [donkirkby/live-py-plugin#317] opened 2021-09-22 01:31 UTC
On Ubuntu 20.04.2 LTS, I installed `live-py-plugin` with the following configuration and use it with [`elpy`](https://github.com/jorgenschaefer/elpy) side-by-side:

```emacs-lisp
(use-package live-py-mode
  :hook (python-mode . live-py-mode)) 
```

But this will cause the failure of `user-error: Current buffer has no associated file` when I hit `C-c C-c` to evaluate the current buffer, as shown below:

![image](https://user-images.githubusercontent.com/11155854/134269429-569e050d-8ecc-47db-a474-c6c7f60b452d.png)

Any hints for this problem?

Regards,
HZ

**Comment by donkirkby** [comment] 2021-09-22 04:33
Thanks for reporting the bug. It sounds like a duplicate of #299, but in a different mode.

**Closed by donkirkby** 2021-09-22 04:33 UTC
Labels: duplicate
