### ISSUE TITLE
add support for org babel source blocks

### ISSUE THREAD

**Issue by ramestica** [donkirkby/live-py-plugin#259] opened 2020-02-03 19:42 UTC
# What I did
Edit a babel block in an org file (org-edit-special). This will open a second buffer with only the code in the block from where org-edit-special was invoked. In this new buffer enable live-py-mode.

# What happened
the live buffer pops-up but it displays the following:

------------------------------------------------------------- |
FileNotFoundError: [Errno 2] No such file or directory: 'Src' |
------------------------------------------------------------- |

# What I wanted to happen
I expected live-py-mode not to require an actual file on disk but just a buffer to do its magic.

# My environment
* Emacs 26.3
* Ubuntu 18.04
* Python 3.6.8
* Org mode 9.1.9

**Comment by donkirkby** [comment] 2020-02-04 03:52
Thanks for the bug report. I'm having trouble reproducing the problem, though, because I get this error:

    Current buffer has no associated file

That's coming from [my code], so I don't see how you can get the error you reported. What version of `live-py-mode` are you using, and have you changed the source code?

[my code]: https://github.com/donkirkby/live-py-plugin/blob/v4.0.1/emacs-live-py-mode/live-py-mode.el#L315-L316

**Comment by ramestica** [comment] 2020-02-04 04:15
thanks for the followup.

I installed from melpa and I see that live-py-version is nil. But in package-list-packages the reported version is 20200127.659. 

I have not modified the code.

I replaced my local live-py-mode.el file (removed elc) by the code in your link above and the result remains the same for me, that is,

------------------------------------------------------------- |
FileNotFoundError: [Errno 2] No such file or directory: 'Src' |
------------------------------------------------------------- |

**Comment by donkirkby** [comment] 2020-02-04 04:20
OK, it must be a difference between your version of org mode and mine. I'll try to upgrade mine.

**Comment by donkirkby** [comment] 2020-02-08 07:05
It looks like this could theoretically work, and I added support to `space_tracer` to run without a source file. To call it, you run it like this:

    space_tracer -

That will read the source code from stdin, and trace it.

However, when I tried adjusting the Emacs mode to run without a current file, it was a mess! Many places call `buffer-file-name`, and my attempts to fake that failed. For now, I'm going to close this as "won't fix". If someone with more Emacs patience than I have wants to take a crack at this, I'll reopen the issue.

Sorry I couldn't help more.

**Comment by donkirkby** [comment] 2020-02-08 16:27
It occurs to me that you don't have the problem that was blocking me: no `buffer-file-name`. If I can replicate your setup, I might be able to make this work, so I'm reopening the issue.

Please tell me what other MELPA packages you have installed, and what versions you have. Please also give me a minimal org file that causes the problem, and an explicit set of steps that you use to launch Emacs, open your org file, and launch live coding mode.

I'm testing with this environment:

* Emacs 26.3
* org package 9.3.3
* Ubuntu 18.04
* Python 3.6.9

**Comment by ramestica** [comment] 2020-02-08 23:15
just let me know if you think that this is not what you expected. But instead of collecting all my installed modules, I have instead ran emacs from scratch by removing my .emacs.d directory. This should bring me to a default emacs, which I built from source time ago.

I have now installed live-py following the instructions in "Installing the Emacs mode without MELPA". Copying to my empty .emacs.d did not work exactly as shown in the instructions; because my cloned version contains no py files under plugin/PySrc, just a  space_tracer directory. My procedure was then just to copy live-py-mode.el into my empty new .emacs.d and then I followed the rest of the instructions until opening emacs and from there opening my live.org file (shown below).

Moving the pointer to the source block and then typing C-' opens up the Org Src buffer and evaluating live-py-mode here produces the following message:

> directory-file-name: Wrong type argument: stringp, nil
> Error in post-command-hook (live-py-post-command-function): (wrong-type-argument stringp nil)

And in this case I do not get a live-py buffer with the error as in my original posting. That is, removing all my installed modules changed the behavior but still it does not work.

`* foo
  #+begin_src python
    def foo():
	print('foo')
  #+end_src
`

- emacs 26.3
- org 9.1.9
- Ubuntu 18.04
- Python 3.6.8

**Comment by donkirkby** [comment] 2020-02-09 06:22
Thanks for doing all that work. The instructions for installing without MELPA were out of date, sorry about that. I've updated them now, and I might create a branch for you to test.

Before that, please try this with your plain Emacs (no packages).

1. Launch it like this in a directory where you have write permission.

       emacs -nw scratch.org

2. Type in some content.

       Some example text.
       
       #+BEGIN_SRC python
         print('Hello')
       #+END_SRC

3. Type `M-: buffer-file-name`, and tell me what you see in the minibuffer. I see `"/path/to/folder/scratch.org"`
4. In the code block, type `C-c '` to edit it in a separate buffer.
5. In the new buffer, type `M-: buffer-file-name`, and tell me what you see in the minibuffer. I see `nil`.

By the way, is this the first time you've tried to use the live coding mode, or do you use it on regular Python files as well? I'm always curious how people are using it.

**Comment by ramestica** [comment] 2020-02-15 19:07
For #3 I see the same. For #4 I do not see nil. I see the following instead:

> "/path/to/folder/scratch.org[*Org Src scratch.org[ python ]*]"

It is the first time I'm trying the live coding mode. For almost 'live' python coding I use org babel jupyter-python. I learned about live-py-plugin from Using Emacs Episode 65 and decided to give it a try. As a possible faster workflow for specific situations.

**Comment by donkirkby** [comment] 2020-06-29 05:17
Good news! I was able to reproduce your behaviour when I installed Emacs 26.3 as a snap in Ubuntu 18.04.

**Closed** 2020-06-29 05:20 UTC

**Comment by OmarAshkar** [comment] 2021-04-02 03:47
@donkirkby Hi, I am wondering if this was fixed cause I am still getting 

```
Current buffer has no associated file
```
I am using melpa installation!

**Comment by donkirkby** [comment] 2021-04-02 04:39
Yes, @OmarAshkar I thought it was fixed. If you're seeing a similar error, please open a new issue describing how to reproduce it, and mention that it's similar to this issue.
